### ISSUE TITLE
What is this suspicious file? Backdoor?

### ISSUE THREAD

**Issue by Xanuman** [meshbird/meshbird#130]
At the end of the file, I noticed a suspicious piece of code

meshbird-2.3\protocol\protocol.pb.go

```
fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
```

Too lazy to decode it. Developer, what's there?

**Comment by miolini** [comment]
This is autogenerated source code by grpc-go.

**Comment by Xanuman** [comment]
Ога, понял.
Однако гуглоиды намутили с этим своим golang
Старею однако. Вона чо напридумывали
А так то окинешь код взглядом. "Пэйлоад", закодированные структуры.
И сразу напрягаешься.

Можно тогда закрывать
