### ISSUE TITLE
Crosscompile via goxc to all platforms

### ISSUE THREAD

**Issue by miolini** [meshbird/meshbird#43]

**Comment by ttyh061** [comment]
Hi miolini:

You could use go directly to do cross-compile think like goxc, For instance the below line for building a linux 64 binary:

env GOOS=linux GOARCH=amd64 go build

**Comment by miolini** [comment]
Hi!
Thank you for advice. We have used it in dev branch already
https://github.com/meshbird/meshbird/blob/dev/Makefile#L19

**Comment by gen1us2k** [comment]
Done in dev branch
