### ISSUE TITLE
Create consistent data storage for storing services data

### ISSUE THREAD

**Issue by miolini** [meshbird/meshbird#50]

**Comment by faddat** [comment]
+1

If the virtual networking also served the role of etcd/consul/"cluster store" that's one less thing to configure, and today,one less thing to configure is great.  Meshbird could be a "insta-cluster."

**Comment by miolini** [comment]
Yes. Common purpose for storage is create additional services on top of it. Load balancer services, for example.

**Comment by faddat** [comment]
We will test this on our systems alongside of & alternatively to weave.  I try to give detailed, complete feedback.  If there is anything that you'd like us to test specifically, please don't hesitate to let us know.  Reading your roadmap, it sounds like you are (wisely) aggressively seeking to make meshbird into a sort of all-in-one clustering tool that covers many of the most difficult aspects of clustering and makes them simple by combining them in a logical fashion.  

*applause!*
