### ISSUE TITLE
Building fails: unknown cli.Command field ‘ArgsUsage’

### ISSUE THREAD

**Issue by kseistrup** [meshbird/meshbird#51]
```sh
$ go get github.com/meshbird/meshbird
# github.com/meshbird/meshbird
.local/share/go/src/github.com/meshbird/meshbird/main.go:35: unknown cli.Command field 'ArgsUsage' in struct literal
.local/share/go/src/github.com/meshbird/meshbird/main.go:55: unknown cli.Command field 'ArgsUsage' in struct literal
.local/share/go/src/github.com/meshbird/meshbird/main.go:67: unknown cli.StringFlag field 'Destination' in struct literal
.local/share/go/src/github.com/meshbird/meshbird/main.go:74: unknown cli.StringFlag field 'Destination' in struct literal
```

```sh
$ go version
go version go1.5.3 linux/amd64
$ uname -a
Linux fsm 4.3.3-3-ARCH #1 SMP PREEMPT Wed Jan 20 08:12:23 CET 2016 x86_64 GNU/Linux
```

**Comment by miolini** [comment]
Hey @kseistrup 
Is this error happened at Jan 20? Because I have checked it in clean docker image

```$ docker run --rm -it golang:1.5 bash
root@fce27d9b7f39:/go# go get github.com/meshbird/meshbird
```
no errors

**Comment by kseistrup** [comment]
It happened a few minutes before I reported the issue.

**Comment by miolini** [comment]
Do you have any specific options on your machine?

**Comment by kseistrup** [comment]
Nope, I just ran `go get github.com/meshbird/meshbird`.

**Comment by miolini** [comment]
Could you please try to build it on clean docker environment as I describe in my first comment? I have to find out.

**Comment by kseistrup** [comment]
I'm not using docker. I'm building from a plain `bash` prompt.

I'll try and wipe all caches and start again…

**Comment by miolini** [comment]
Try to run build with -v flag.

**Comment by kseistrup** [comment]
I removed all dirs in the `$GOPATH` directory, and now it built.  There must have been some rotten packages in that directory.  Thanks for your help!

**Comment by miolini** [comment]
No problem
