### ISSUE TITLE
WebUI

### ISSUE THREAD

**Issue by miolini** [meshbird/meshbird#59]
Create basic WebUI for showing topology and metrics

**Comment by faddat** [comment]
zomg did you just use the world topology in this context?  

+100.

**Comment by abale** [comment]
Accepting patches 

![image](https://cloud.githubusercontent.com/assets/12463120/15875452/e8078cda-2cd5-11e6-9920-2d3ab91398d2.png)

**Comment by miolini** [comment]
👍
