### ISSUE TITLE
Panic at some cases

### ISSUE THREAD

**Issue by ptqa** [meshbird/meshbird#63]
I'm facing runtime panic if I try to login to instance via ssh and run dmesg command. I have only 2 nodes in network. It may be related to known bug with `Decode error: unknown type`.

Logs and trace are available here https://gist.github.com/ptqa/cb1868497addc6b6e784

BUT if I change mtu to small value (like 500) It does not fail.

**Comment by miolini** [comment]
New version 2.0 released.
