### ISSUE TITLE
Centos 7 without ifconfig

### ISSUE THREAD

**Issue by miry** [meshbird/meshbird#75]
By default there are no `ifconfig` in the new distributive of Centos 7. There is `ip` command.

```
[main] 2016/07/13 10:15:02 node start error: Initialision of iface finished with error: create interface  err: tun interface  up err: exec: "ifconfig": executable file not found in $PATH
```

It would great to see all requirements to run application.

**Comment by miolini** [comment]
Hey @miry! Could you please send a patch to switch to ip command?

**Comment by mitchjacksontech** [comment]
ifconfig is provided by the net-tools package.  `sudo yum -y install net-tools` will solve your problem.
