### ISSUE TITLE
CBC ciphertext not authenticated, making the system insecure

### ISSUE THREAD

**Issue by leonklingele** [meshbird/meshbird#87]
It [looks like](https://github.com/meshbird/meshbird/blob/41a032c55c07b4b609cfa84d8ea365d4c58a8d59/secure/crypt.go#L9) you're using unauthenticated AES-CBC. This scheme is vulnerable to [bit flipping attacks](https://en.wikipedia.org/wiki/Bit-flipping_attack).

Either authenticate the ciphertext in Encrypt-Then-MAC fashion or switch to using a AEAD cipher like AES-GCM: https://github.com/gtank/cryptopasta/blob/master/encrypt.go

**Comment by miolini** [comment]
New version 2.0 released with AES-256-GCM.
