### ISSUE TITLE
/usr/local/bin/meshbird: /usr/local/bin/meshbird: cannot execute binary file

### ISSUE THREAD

**Issue by seekr** [meshbird/meshbird#88]
installed on macos using
`sudo curl https://meshbird.com/install.sh | sh`

then `sudo meshbird new` 

returns:
`/usr/local/bin/meshbird: /usr/local/bin/meshbird: cannot execute binary file`

Any help?

**Comment by gen1us2k** [comment]
We support only linux in this script. We are working on #52, #42 and #40. 
But as a solution you can build project by yourself.
