### ISSUE TITLE
Can't run on macOS

### ISSUE THREAD

**Issue by wxdao** [meshbird/meshbird#90]
Sierra 10.12.4 Beta (16E163f)

wxdao-mac:~ wxdao$ MESHBIRD_KEY="feebd823ad9c98af6e5c5d8d533591690a070000ffff0000" meshbird --loglevel info join
2017/02/26 01:05:13 INF [main] state restored, &{Secret:0xc4200c7920 ListenPort:51637 PrivateIP:10.7.98.35}
2017/02/26 01:05:13 INF [local] initializing net-table service
2017/02/26 01:05:13 INF [local] initializing listener service
2017/02/26 01:05:13 INF [listener] listening on 51638 port
2017/02/26 01:05:13 INF [local] running "net-table" service
2017/02/26 01:05:13 INF [local] initializing discovery-dht service
2017/02/26 01:05:13 INF [local] initializing iface service
/dev/tun0
/dev/tun1
/dev/tun2
2017/02/26 01:05:13 INF [local] running "listener" service
/dev/tun3
/dev/tun4
/dev/tun5
/dev/tun6
/dev/tun7
/dev/tun8
/dev/tun9
2017/02/26 01:05:13 INF [local] running "discovery-dht" service
2017/02/26 01:05:13 FTL [main] error on local node start, initialization of "iface" finished with error: create new tun interface %!s(*network.Interface=<nil>) err: open /dev/tun9: no such file or directory

Same result with sudo.

**Comment by wxdao** [comment]
I modify the code so it uses utun in macOS now #92 @miolini

**Comment by wxdao** [comment]
This issue can be closed now @miolini

**Comment by jvsteiner** [comment]
Having a similar looking issue on Sierra:

```
jvsmb:dhtfiles jamie$ MESHBIRD_KEY="075164337e1bb1857e60d50ff8eb05640a070000ffff0000" meshbird --loglevel info join
2017/06/09 18:48:24 INF [main] state restored, &{Secret:0xc4200e2760 ListenPort:5538 PrivateIP:10.7.70.151}
2017/06/09 18:48:24 INF [local] initializing net-table service
2017/06/09 18:48:24 INF [local] initializing listener service
2017/06/09 18:48:24 INF [listener] listening on 5539 port
2017/06/09 18:48:24 INF [local] running "net-table" service
2017/06/09 18:48:24 INF [local] initializing discovery-dht service
2017/06/09 18:48:24 INF [local] initializing iface service
2017/06/09 18:48:24 INF [local] running "listener" service
2017/06/09 18:48:24 INF [local] running "discovery-dht" service
2017/06/09 18:48:24 FTL [main] error on local node start, initialization of "iface" finished with error: tun interface  up err: up interface  err: exit status 1
```
