### ISSUE TITLE
unable to dial, i/o timeout

### ISSUE THREAD

**Issue by letenkov** [meshbird/meshbird#91]
2017/03/10 15:03:07 DBG [UPnP] trying to map port 5226...
2017/03/10 15:03:09 DBG [discovery-dht] new peer "94.245.175.196:26900" received
2017/03/10 15:03:09 DBG [public 94.245.175.196:26901] trying to connect...
2017/03/10 15:03:09 DBG [discovery-dht] new peer "94.245.175.196:5225" received
2017/03/10 15:03:09 DBG [public 94.245.175.196:5226] trying to connect...
2017/03/10 15:03:11 DBG [discovery-dht] new peer "107.21.196.252:39101" received
2017/03/10 15:03:11 DBG [public 107.21.196.252:39102] trying to connect...
2017/03/10 15:03:13 DBG [discovery-dht] new peer "37.115.248.9:17428" received
2017/03/10 15:03:13 DBG [public 37.115.248.9:17429] trying to connect...
2017/03/10 15:03:19 ERR [public 94.245.175.196:26901] unable to dial, i/o timeout
2017/03/10 15:03:19 INF [net-table] unable connect 94.245.175.196:26900 err: i/o timeout
2017/03/10 15:03:19 ERR [public 94.245.175.196:5226] unable to dial, i/o timeout
2017/03/10 15:03:19 INF [net-table] unable connect 94.245.175.196:5225 err: i/o timeout
2017/03/10 15:03:21 ERR [public 107.21.196.252:39102] unable to dial, i/o timeout
2017/03/10 15:03:21 INF [net-table] unable connect 107.21.196.252:39101 err: i/o timeout
2017/03/10 15:03:23 DBG [discovery-dht] new peer "78.197.149.2:33426" received
2017/03/10 15:03:23 DBG [public 78.197.149.2:33427] trying to connect...
2017/03/10 15:03:23 ERR [public 37.115.248.9:17429] unable to dial, i/o timeout
2017/03/10 15:03:23 INF [net-table] unable connect 37.115.248.9:17428 err: i/o timeout
2017/03/10 15:03:33 ERR [public 78.197.149.2:33427] unable to dial, i/o timeout
2017/03/10 15:03:33 INF [net-table] unable connect 78.197.149.2:33426 err: i/o timeout
2017/03/10 15:04:07 DBG [discovery-dht] sending request...

**Comment by wxdao** [comment]
It's ok. This happens when it trys to connect as many trackers and some are down or blocked.
